import Foundation

/// Shares only concurrent work. Completed results are removed before callers resume.
actor InFlightRequests<Key: Hashable & Sendable, Value: Sendable> {
    private struct Entry {
        let generation: UUID
        let task: Task<Void, Never>
        var waiters: [UUID: CheckedContinuation<Value, any Error>]
    }
    private var entries: [Key: Entry] = [:]
    var waitingCount: Int { entries.values.reduce(0) { $0 + $1.waiters.count } }

    func value(for key: Key, operation: @escaping @Sendable () async throws -> Value) async throws -> Value {
        let waiterID = UUID()
        let value: Value = try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                if Task.isCancelled { continuation.resume(throwing: CancellationError()); return }
                if entries[key] != nil {
                    entries[key]?.waiters[waiterID] = continuation
                } else {
                    let generation = UUID()
                    let task = Task {
                        let result: Result<Value, any Error>
                        do { result = .success(try await operation()) }
                        catch { result = .failure(error) }
                        self.finish(key: key, generation: generation, result: result)
                    }
                    entries[key] = Entry(generation: generation, task: task, waiters: [waiterID: continuation])
                }
            }
        } onCancel: {
            Task { await self.cancel(key: key, waiterID: waiterID) }
        }
        try Task.checkCancellation()
        return value
    }

    private func finish(key: Key, generation: UUID, result: Result<Value, any Error>) {
        guard let entry = entries[key], entry.generation == generation else { return }
        entries.removeValue(forKey: key)
        for waiter in entry.waiters.values { waiter.resume(with: result) }
    }

    private func cancel(key: Key, waiterID: UUID) {
        guard let waiter = entries[key]?.waiters.removeValue(forKey: waiterID) else { return }
        waiter.resume(throwing: CancellationError())
        if entries[key]?.waiters.isEmpty == true {
            entries.removeValue(forKey: key)?.task.cancel()
        }
    }
}

/// All fields generated by HTTPRequestBuilder that can affect the response or deadline.
struct HTTPRequestIdentity: Hashable, Sendable {
    private struct Header: Hashable, Sendable { let name: String; let value: String }
    private let url: URL?
    private let method: String?
    private let headers: [Header]
    private let body: Data?
    private let timeout: TimeInterval
    private let cachePolicy: UInt

    init(_ request: URLRequest) {
        url = request.url
        method = request.httpMethod
        headers = (request.allHTTPHeaderFields ?? [:]).map {
            Header(name: $0.key.lowercased(), value: $0.value)
        }.sorted { $0.name < $1.name }
        body = request.httpBody
        timeout = request.timeoutInterval
        cachePolicy = request.cachePolicy.rawValue
    }
}
